version: '3.8'

services:
  mongo1:
    image: mongo:5
    container_name: mongo1
    ports:
      - "27017:27017"
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo1

  mongo2:
    image: mongo:5
    container_name: mongo2
    ports:
      - "27018:27017"
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo2

  mongo3:
    image: mongo:5
    container_name: mongo3
    ports:
      - "27019:27017"
    networks:
      - mongoCluster
    command: mongod --replSet myReplicaSet --bind_ip localhost,mongo3

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo1:27017,mongo2:27017,mongo3:27017/DBLP?replicaSet=myReplicaSet
    networks:
      - mongoCluster

networks:
  mongoCluster:
    driver: bridge
